s = {1,2,3,4}
print(s)
s = set(('a',1,'b',2))
print(s)
s = set(['apple', 'banana', 'apple'])
print(s)
s = set({'早安':'Good Morning', '你好':'Hello'})
print(s)
s = set('racecar')
print(s)
s = set('tiger')
print(s)
s.add('z')
print(s)
s.remove('t')
print(s)
