待辦事項 = []
工作 = input('請輸入待辦事項？')
待辦事項.append(工作)
工作 = input('請輸入待辦事項？')
待辦事項.append(工作)
工作 = input('請輸入待辦事項？')
待辦事項.append(工作)
工作 = input('請輸入待辦事項？')
待辦事項.append(工作)
工作 = input('請輸入待辦事項？')
待辦事項.append(工作)
print(待辦事項.pop(0), 待辦事項.pop(0), 待辦事項)
print(待辦事項.pop(), 待辦事項)
